[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"
